project:
  type: website
  output-dir: docs

website:
  title: "Analyse de parcours de soins IC"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: methode.qmd
        text: Méthodes
      - href: resultat.qmd
        text: Analyse & Résultats

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true